### ISSUE TITLE
ERROR! Unexpected Exception: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by walkerwzy** [jlund/streisand#748]
I do a fresh install on a existing server with a reinstall ubuntu, 19G disk space left, and got the error:
```
ERROR! Unexpected Exception: [Errno 28] No space left on device
```
my local machine has 18G disk space

=========

```
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/site-packages/ansible/cli/playbook.py", line 152, in run
    pbex = PlaybookExecutor(playbooks=self.args, inventory=inventory, variable_manager=variable_manager, loader=loader, options=self.options, passwords=passwords)
  File "/usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 59, in __init__
    self._tqm = TaskQueueManager(inventory=inventory, variable_manager=variable_manager, loader=loader, options=options, passwords=self.passwords)
  File "/usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 102, in __init__
    self._final_q = multiprocessing.Queue()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
```

**Comment by cpu** [comment]
I suspect it's the local machine that Ansible believes doesn't have space on the device.

I would recommend you use the [Ansible support](http://docs.ansible.com/ansible/community.html) channels to try and get help with this as it's not Streisand related and I'm unsure of the cause.

Thanks!
